apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: yazanalsharif12/expiration:latest
          env:
            - name: KAFKA_URL
              value: kafka-srv:29092
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: CLUSTER_ID
              value: ticketing
            - name: CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: Node_Env
              value: "test"
            - name: REDIS_URL
              value: 'redis://expiration-redis-srv'
           
